In [1]:
print("Hello World")

Hello World


# Importing ***NumPy***

In [2]:
import numpy as np

# Basic 1d array

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


# Indexing is same as in list or tuple

In [5]:
print(a[0])

1


# Basic 2d array

In [6]:
a = np.array([[ 1, 99,  3],[ 1,  2,  4],[2, 45, 67]])
print(a)

[[ 1 99  3]
 [ 1  2  4]
 [ 2 45 67]]


# Dimensions

In [7]:
print(a.ndim)

2


# Number of elements in array

In [8]:
print(a.size)

9


# Size of elments in array

In [9]:
print(a.itemsize)

8


# Shape of array

In [10]:
print(a.shape)

(3, 3)


# Pick data-type of array elements

In [11]:
a = np.array([[ 1, 99,  3],[ 1,  2,  4],[2, 45, 67]], dtype=np.float64)
print(a)

[[ 1. 99.  3.]
 [ 1.  2.  4.]
 [ 2. 45. 67.]]


# Make a matrix of 0's

In [12]:
a = np.zeros((3,4), dtype=np.uint8)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Make a matrix of 1's

In [13]:
a = np.ones((3,4), dtype=np.uint16)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# Make an array in a range

In [14]:
a = np.arange(5)
print(a)

a = np.arange(1,5)
print(a)

a = np.arange(1,5,2)
print(a)

a = np.arange(5,1,-1)
print(a)

# arange() is similar to range()

[0 1 2 3 4]
[1 2 3 4]
[1 3]
[5 4 3 2]


# String add

In [15]:
a = np.array(["Hello", "NumPy"])
b = np.array([" World", " Rocks!"])
result = np.char.add(a, b)
print(result)

['Hello World' 'NumPy Rocks!']


# String multiply

In [16]:
a = np.array(["Hello", "NumPy"])
result = np.char.multiply(a, 3)
print(result)

['HelloHelloHello' 'NumPyNumPyNumPy']


Write a function using NumPy that takes a string and a number as input, and returns the string with its characters repeated. For example, if the input is 'Hi' and 3, the output should be 'HHHiii'

In [17]:
def repeat_string(input_str, n):

    char_array = np.array(list(input_str))

    repeated_array = np.char.multiply(char_array, n)
    result = ''.join(repeated_array)
    return result

output = repeat_string("Hi", 3)
print(output)

HHHiii


# Centering string

In [18]:
a = np.char.center("Hello", 10, fillchar='*')
print(a)
# here 10 is total, so len(stirng) + filler

**Hello***


# Capitalize

In [19]:
import numpy as np

result = np.char.capitalize(["hello there", "world is good"])
print(result)

['Hello there' 'World is good']


# Title

In [20]:
result = np.char.title("hello numpy world")
print(result)

Hello Numpy World


# Upper

In [21]:
result = np.char.upper("hello numpy")
print(result)

HELLO NUMPY


# Lower

In [22]:
result = np.char.lower("HELLO NUMPY")
print(result)

hello numpy


# Split

In [23]:
result = np.char.split("Hello NumPy World")
print(result)
# default split is space

result = np.char.split("apple,banana,grape", sep=",")
print(result)

['Hello', 'NumPy', 'World']
['apple', 'banana', 'grape']


# Split lines

In [24]:
result = np.char.splitlines("Hello\nNumPy\nWorld")
print(result)

['Hello', 'NumPy', 'World']


# Split each character

In [25]:
result = np.array(list("NumPy"))
print(result)

['N' 'u' 'm' 'P' 'y']


# Strip

In [26]:
result = np.char.strip("  Hello NumPy  ")
print(result)
# default strip is space

result = np.char.strip("$$$Hello NumPy$$$", "$")
print(result)

Hello NumPy
Hello NumPy


# Join string

In [27]:
result = np.char.join("-", "NumPy")
print(result)

N-u-m-P-y


# Join array

In [28]:
result = np.char.join(":", ["Hello", "World"])
print(result)

['H:e:l:l:o' 'W:o:r:l:d']


# Replace

In [29]:
result = np.char.replace(["apple pie", "banana pie"], "pie", "cake")
print(result)

result = np.char.replace("Hello NumPy", "NumPy", "World")
print(result)

['apple cake' 'banana cake']
Hello World


# Changing array shape

In [30]:
a = np.arange(9)
print("Orignal: ", a)

b = a.reshape(3,3)
print("Modified")
print(b)

Orignal:  [0 1 2 3 4 5 6 7 8]
Modified
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Flatten

In [31]:
print(b.flatten())

# C -> row major order(default)

print(b.flatten(order = 'F'))
# F - column major order

[0 1 2 3 4 5 6 7 8]
[0 3 6 1 4 7 2 5 8]


# Transpose

In [32]:
a = np.arange(12).reshape(3,4)
print("Orignal:")
print(a)
print("Transpose:")
print(np.transpose(a))

Orignal:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# Rollaxis

In [33]:
a = np.arange(24).reshape(2, 3, 4)
print("Orignal shape:",a.shape)

a = np.rollaxis(a, axis=2, start=0)
# this moves axis in 2nd place to 0th place
print("After shape:",a.shape)

Orignal shape: (2, 3, 4)
After shape: (4, 2, 3)


# Swapaxes

In [34]:
a = np.arange(24).reshape(2, 3, 4)
print("Orignal shape:",a.shape)

a = np.swapaxes(a, axis1=0,axis2=2)
# swaps axes 0 and 2
print("After shape:",a.shape)

Orignal shape: (2, 3, 4)
After shape: (4, 3, 2)


# Arithmetic Operations

In [35]:
a = np.arange(9).reshape(3,3)
b = np.array([10,100,1000])
print("a:\n",a)
print("b:\n",b)

a:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b:
 [  10  100 1000]


# Add

In [36]:
print(np.add(a,b))

[[  10  101 1002]
 [  13  104 1005]
 [  16  107 1008]]


# Subtract

In [37]:
print(np.subtract(a,b))

[[ -10  -99 -998]
 [  -7  -96 -995]
 [  -4  -93 -992]]


# Multiply

In [38]:
print(np.multiply(a,b))

[[   0  100 2000]
 [  30  400 5000]
 [  60  700 8000]]


# Divide

In [39]:
print(np.divide(a,b))

[[0.    0.01  0.002]
 [0.3   0.04  0.005]
 [0.6   0.07  0.008]]


# Slicing

In [40]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [41]:
print(a[4:])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [42]:
print(a[:4])

[0 1 2 3]


In [43]:
print(a[5])

5


In [44]:
s = slice(2,12,3)
print(a[s])

[ 2  5  8 11]


# Iterating over Array

In [45]:
a = np.arange(0,45,5).reshape(3,3)
print(a)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]


In [46]:
for i in np.nditer(a):
    print(i)

0
5
10
15
20
25
30
35
40


# Iterating C-order(row order) default

In [47]:
for i in np.nditer(a, order='C'):
    print(i)

0
5
10
15
20
25
30
35
40


# Iterating F-order(Column order)

In [48]:
for i in np.nditer(a, order='F'):
    print(i)

0
15
30
5
20
35
10
25
40


# Concatanate

In [49]:
a = np.arange(1,5).reshape(2,2)
print(f"a\n{a}")
b = np.arange(5,9).reshape(2,2)
print(f"b\n{b}")

a
[[1 2]
 [3 4]]
b
[[5 6]
 [7 8]]


# Concatanate along axis=0(default)

In [50]:
print(f"\nConcanat a and b axis=0\n{np.concatenate((a,b))}")


Concanat a and b axis=0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Concatanate along axis=1

In [51]:
print(f"\nConcanat a and b axis=1\n{np.concatenate((a,b), axis=1)}")


Concanat a and b axis=1
[[1 2 5 6]
 [3 4 7 8]]


# Split into Equal Parts

In [52]:
a = np.arange(9)
print(np.split(a,3))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


# Split into Unequal Parts Using Indices

In [53]:
print(np.split(a, [2, 5]))

# it will give 2 elements then till 5 so (5 - 2 = 3)
# 2(0,1) 3(2,3,4) remaining

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8])]


In [54]:
print(np.split(a, [2, 5, 7]))
# 2's array, 3's array, 2's array
# 2 , 3(5-2=3), 7(7-5=2), remaining

[array([0, 1]), array([2, 3, 4]), array([5, 6]), array([7, 8])]


# Split a 2D Array

In [55]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
# Split along rows (default axis=0)
print(np.split(a, 2))

# Split along columns (axis=1)
print(np.split(a, 2, axis=1))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


# Resize

In [56]:
a = np.array([[1,2,3],[4,5,6]])
print(f"a\n{a}\nshape:{a.shape}")

b = np.resize(a,(3,2))
print(f"b\n{b}\nshape:{b.shape}")

a
[[1 2 3]
 [4 5 6]]
shape:(2, 3)
b
[[1 2]
 [3 4]
 [5 6]]
shape:(3, 2)


# Resize not matching dimension

In [57]:
c = np.resize(a,(3,3))
print(f"c\n{c}\nshape:{c.shape}")

# it starts repeating 

c
[[1 2 3]
 [4 5 6]
 [1 2 3]]
shape:(3, 3)


# Linspace

In [58]:
a = np.linspace(0,10,5)
# generates equally spaced values between 0 - 10 (both included) and 5 numbers
print(a)

[ 0.   2.5  5.   7.5 10. ]


# Sum

In [59]:
a = np.array([[1,2,3],[4,5,6]])
print(a.sum(axis=0))
print(a.sum(axis=1))

[5 7 9]
[ 6 15]


# Square root

In [60]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


# Standard Deviation

In [61]:
print(np.std(a))

1.707825127659933


# Log

In [62]:
print(np.log10(a))
print(np.log2(a))

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]]


# ***The End***